"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const cors_1 = __importDefault(require("cors"));
const routes_1 = __importDefault(require("./routes"));
const connection_1 = __importDefault(require("./persistence/connection"));
const swagger_ui_express_1 = __importDefault(require("swagger-ui-express"));
const swagger_output_json_1 = __importDefault(require("./swagger_output.json"));
const app = (0, express_1.default)();
const PORT = process.env.PORT || 80;
const jsonParser = express_1.default.json();
(0, connection_1.default)();
app.use((0, cors_1.default)());
app.use(jsonParser);
app.use('/api', routes_1.default);
app.use('/doc', swagger_ui_express_1.default.serve, swagger_ui_express_1.default.setup(swagger_output_json_1.default));
app.get('/', (_, res) => res.send('Ping!'));
app.listen(PORT, () => console.log(`Server Running on PORT: ${PORT}`));
